version: "3.8"
name: authentification
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    ports:
      - 5432
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres