on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  docker:
    runs-on: ubuntu-22.04
    needs: [build]
    env:
      IMAGE_NAME: authentification-service
      CONTAINER_NAME: authentification-service
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
        - uses: actions/checkout@v3
        - name: Build Docker image
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and export to Docker
          uses: docker/build-push-action@v5
          with:
            context: .
            load: true
            tags: ${{ env.TEST_TAG }}
        - name: Test
          run: |
            docker run --rm ${{ env.TEST_TAG }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ env.LATEST_TAG }}


